# Generated by Django 6.1.1

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("auth", "0012_alter_user_first_name_max_length")]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("username", models.CharField(error_messages={"unique": "A user with that username already exists."}, help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="username")),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                ("is_staff", models.BooleanField(default=False, help_text="Designates whether the user can log into this admin site.", verbose_name="staff status")),
                ("is_active", models.BooleanField(default=True, help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.", verbose_name="active")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"db_table": "wallet_user", "verbose_name": "user", "verbose_name_plural": "users"},
            managers=[("objects", django.contrib.auth.models.UserManager())],
        ),
        migrations.CreateModel(
            name="MoneyLocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("location_type", models.CharField(choices=[("bank", "Bank"), ("cash", "Cash"), ("travel_card", "Travel Card"), ("change_cash", "Change Cash")], default="bank", max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("sql", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="QueryExecutionLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("query", models.TextField()),
                ("status", models.CharField(default="success", max_length=20)),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("total_balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("money_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="accounts", to="wallet.moneylocation")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("spendable", "Spendable"), ("savings", "Savings")], max_length=20)),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="wallet.account")),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subcategories", to="wallet.category")),
            ],
            options={"ordering": ["category__name", "name"]},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("is_custom", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="wallet.category")),
                ("subcategory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="items", to="wallet.subcategory")),
            ],
            options={"ordering": ["category__name", "subcategory__name", "name"]},
        ),
        migrations.CreateModel(
            name="MoneyPool",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("allocation_type", models.CharField(choices=[("spendable", "Spendable"), ("savings", "Savings")], max_length=20)),
                ("current_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="money_pools", to="wallet.account")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="money_pools", to="wallet.owner")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="money_pools", to="wallet.moneylocation")),
            ],
            options={"ordering": ["owner__name", "location__name", "allocation_type"]},
        ),
        migrations.CreateModel(
            name="FoodProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("food_type", models.CharField(choices=[("food", "Food"), ("drink", "Drink")], default="food", max_length=10)),
                ("food_group", models.CharField(choices=[("main_meal", "Main Meal"), ("snack", "Snack"), ("bakery", "Bakery"), ("fruit", "Fruit"), ("vegetable", "Vegetable"), ("protein", "Protein"), ("beverage", "Beverage"), ("other", "Other")], default="other", max_length=30)),
                ("health_classification", models.CharField(choices=[("healthy", "Healthy"), ("junk", "Junk"), ("neutral", "Neutral"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("sugary", models.CharField(choices=[("yes", "Yes"), ("no", "No"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="food_profile", to="wallet.item")),
            ],
            options={"ordering": ["item__name"]},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("variant", models.CharField(blank=True, default="", max_length=200)),
                ("meal", models.CharField(blank=True, choices=[("breakfast", "Breakfast"), ("lunch", "Lunch"), ("dinner", "Dinner"), ("snack", "Snack"), ("other", "Other")], max_length=20, null=True)),
                ("type", models.CharField(choices=[("deposit", "Deposit"), ("expense", "Expense"), ("allocation", "Allocation"), ("transfer", "Transfer")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="wallet.account")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.owner")),
                ("money_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.moneylocation")),
                ("allocation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.allocation")),
                ("source_pool", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_transactions", to="wallet.moneypool")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.category")),
                ("subcategory", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.subcategory")),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="transactions", to="wallet.item")),
                ("related_tx", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="linked_transactions", to="wallet.transaction")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FoodEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("meal", models.CharField(choices=[("breakfast", "Breakfast"), ("lunch", "Lunch"), ("dinner", "Dinner"), ("snack", "Snack"), ("other", "Other")], max_length=20)),
                ("food_type", models.CharField(choices=[("food", "Food"), ("drink", "Drink")], default="food", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("transaction", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="food_event", to="wallet.transaction")),
            ],
        ),
        migrations.CreateModel(
            name="FoodEventItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("custom_name", models.CharField(blank=True, default="", max_length=200)),
                ("variant", models.CharField(blank=True, default="", max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="wallet.foodevent")),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="wallet.item")),
            ],
        ),
        migrations.AddConstraint(model_name="account", constraint=models.CheckConstraint(condition=models.Q(("total_balance__gte", 0)), name="account_total_non_negative")),
        migrations.AddConstraint(model_name="allocation", constraint=models.UniqueConstraint(fields=("account", "type"), name="unique_account_allocation_type")),
        migrations.AddConstraint(model_name="allocation", constraint=models.CheckConstraint(condition=models.Q(("balance__gte", 0)), name="allocation_balance_non_negative")),
        migrations.AddConstraint(model_name="subcategory", constraint=models.UniqueConstraint(fields=("category", "name"), name="unique_category_subcategory_name")),
        migrations.AddConstraint(model_name="item", constraint=models.UniqueConstraint(fields=("category", "subcategory", "name"), name="unique_category_subcategory_item_name")),
        migrations.AddConstraint(model_name="moneypool", constraint=models.UniqueConstraint(fields=("account", "owner", "location", "allocation_type"), name="unique_account_owner_location_allocation_pool")),
        migrations.AddConstraint(model_name="moneypool", constraint=models.CheckConstraint(condition=models.Q(("current_amount__gte", 0)), name="money_pool_amount_non_negative")),
        migrations.AddConstraint(model_name="foodeventitem", constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="food_event_item_quantity_positive")),
        migrations.AddConstraint(model_name="foodeventitem", constraint=models.CheckConstraint(condition=models.Q(("item__isnull", False)) | ~models.Q(("custom_name", "")), name="food_event_item_requires_item_or_name")),
        migrations.AddConstraint(model_name="transaction", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="transaction_amount_positive")),
        migrations.AddIndex(model_name="transaction", index=models.Index(fields=["-occurred_at", "-created_at"], name="tx_occurred_created_idx")),
        migrations.AddIndex(model_name="transaction", index=models.Index(fields=["account", "-occurred_at"], name="tx_account_occurred_idx")),
        migrations.AddIndex(model_name="transaction", index=models.Index(fields=["type", "-occurred_at"], name="tx_type_occurred_idx")),
    ]
