# Generated by Django 6.1 on 2026-08-23 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_category_transaction_category_item_transaction_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location_type', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash')], default='bank', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_pools', to='wallet.allocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_pools', to='wallet.moneylocation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_pools', to='wallet.owner')),
            ],
            options={
                'ordering': ['owner__name', 'location__name', 'allocation__type'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'location', 'allocation'), name='unique_owner_location_allocation_pool')],
            },
        ),
    ]
