# Generated by Django 6.1 on 2026-08-23 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_item_options_item_description_item_is_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meal',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FoodProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_group', models.CharField(choices=[('drink', 'Drink'), ('main_food', 'Main Food'), ('snack', 'Snack'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('other', 'Other')], default='other', max_length=30)),
                ('health_classification', models.CharField(choices=[('healthy', 'Healthy'), ('junk', 'Junk'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('sugary', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_profile', to='wallet.item')),
            ],
            options={
                'ordering': ['item__name'],
            },
        ),
    ]
