# Generated by Django 6.1 on 2026-08-23 17:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_money_pool_allocation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other')], max_length=20)),
                ('food_type', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink')], default='food', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEventItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('variant', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_category_item_name',
        ),
        migrations.RemoveConstraint(
            model_name='moneypool',
            name='unique_owner_location_allocation_type_pool',
        ),
        migrations.AddField(
            model_name='account',
            name='money_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='wallet.moneylocation'),
        ),
        migrations.AddField(
            model_name='moneypool',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_pools', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='moneypool',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('total_balance__gte', 0)), name='account_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='allocation_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory', 'name'), name='unique_category_subcategory_item_name'),
        ),
        migrations.AddConstraint(
            model_name='moneypool',
            constraint=models.UniqueConstraint(fields=('account', 'owner', 'allocation_type'), name='unique_account_owner_allocation_pool'),
        ),
        migrations.AddConstraint(
            model_name='moneypool',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='money_pool_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddField(
            model_name='foodevent',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_event', to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='foodeventitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallet.foodevent'),
        ),
        migrations.AddField(
            model_name='foodeventitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.item'),
        ),
        migrations.AddConstraint(
            model_name='foodeventitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='food_event_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='foodeventitem',
            constraint=models.CheckConstraint(condition=models.Q(('item__isnull', False), models.Q(('custom_name', ''), _negated=True), _connector='OR'), name='food_event_item_requires_item_or_name'),
        ),
    ]
