# Generated by Django 6.1 on 2026-08-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_seed_standard_wallets'),
        ('wallet', '0013_moneypool_location_types'),
    ]

    operations = [
    ]
