# Generated by Django 6.1 on 2026-08-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_moneypool_location_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='wallet.moneylocation'),
        ),
    ]
