# Generated by Django 6.1 on 2026-08-24 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_fix_account_money_location_not_unique'),
        ('wallet', '0014_merge_20260824_0231'),
    ]

    operations = [
    ]
