# Generated by Django 6.1.1 on 2026-09-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_foodprofile_food_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-occurred_at', '-created_at'], name='tx_occurred_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-occurred_at'], name='tx_account_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', '-occurred_at'], name='tx_type_occurred_idx'),
        ),
    ]
